# Generated by Django 5.2 on 2025-04-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='discord_id',
            field=models.CharField(default='Unknown', max_length=255, unique=True, verbose_name='Discord ID'),
        ),
    ]
