# Generated by Django 5.2 on 2025-04-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_score_discord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='explanation'),
        ),
    ]
