# Generated by Django 5.2 on 2025-04-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='diffficulty',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/', verbose_name='Question Image'),
        ),
    ]
