# Generated by Django 5.2 on 2025-04-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_question_ccna_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ccna_level',
            field=models.IntegerField(choices=[(0, 'Any'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=0, verbose_name='CCNA Level'),
        ),
    ]
