# Generated by Django 5.2 on 2025-04-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_question_ccna_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='explanation',
        ),
        migrations.AddField(
            model_name='answer',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation'),
        ),
    ]
