# Generated by Django 5.2 on 2025-04-12 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_answer_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/%Y/%m/%d/', verbose_name='Question Image'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.SmallIntegerField(default=1, verbose_name='points'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['ccna_level'], name='quiz_questi_ccna_le_9ee059_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active'], name='quiz_questi_is_acti_995386_idx'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('question', 'answer'), name='unique_answer_per_question'),
        ),
    ]
