# Generated by Django 5.2 on 2025-04-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='answers',
        ),
    ]
