# Generated by Django 5.2 on 2025-04-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_rename_answer_answer_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answers',
            new_name='answer',
        ),
    ]
