# Generated by Django 5.2 on 2025-04-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_alter_question_image'),
    ]

    operations = [
    ]
